/**
 * MIT License
 *
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include "States.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char BaiduMapOverlayArcComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayArc> component.
 */
using BaiduMapOverlayArcShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayArcComponentName,
    BaiduMapOverlayArcProps,
    BaiduMapOverlayArcEventEmitter,
    BaiduMapOverlayArcState>;

JSI_EXPORT extern const char BaiduMapOverlayCircleComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayCircle> component.
 */
using BaiduMapOverlayCircleShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayCircleComponentName,
    BaiduMapOverlayCircleProps,
    BaiduMapOverlayCircleEventEmitter,
    BaiduMapOverlayCircleState>;

JSI_EXPORT extern const char BaiduMapOverlayClusterComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayCluster> component.
 */
using BaiduMapOverlayClusterShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayClusterComponentName,
    BaiduMapOverlayClusterProps,
    BaiduMapOverlayClusterEventEmitter,
    BaiduMapOverlayClusterState>;

JSI_EXPORT extern const char BaiduMapOverlayHeatMapComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayHeatMap> component.
 */
using BaiduMapOverlayHeatMapShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayHeatMapComponentName,
    BaiduMapOverlayHeatMapProps,
    BaiduMapOverlayHeatMapEventEmitter,
    BaiduMapOverlayHeatMapState>;

JSI_EXPORT extern const char BaiduMapOverlayInfoWindowComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayInfoWindow> component.
 */
using BaiduMapOverlayInfoWindowShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayInfoWindowComponentName,
    BaiduMapOverlayInfoWindowProps,
    BaiduMapOverlayInfoWindowEventEmitter,
    BaiduMapOverlayInfoWindowState>;

JSI_EXPORT extern const char BaiduMapOverlayMarkerIconComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayMarkerIcon> component.
 */
using BaiduMapOverlayMarkerIconShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayMarkerIconComponentName,
    BaiduMapOverlayMarkerIconProps,
    BaiduMapOverlayMarkerIconEventEmitter,
    BaiduMapOverlayMarkerIconState>;

JSI_EXPORT extern const char BaiduMapOverlayMarkerComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayMarker> component.
 */
using BaiduMapOverlayMarkerShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayMarkerComponentName,
    BaiduMapOverlayMarkerProps,
    BaiduMapOverlayMarkerEventEmitter,
    BaiduMapOverlayMarkerState>;

JSI_EXPORT extern const char BaiduMapOverlayPolygonComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayPolygon> component.
 */
using BaiduMapOverlayPolygonShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayPolygonComponentName,
    BaiduMapOverlayPolygonProps,
    BaiduMapOverlayPolygonEventEmitter,
    BaiduMapOverlayPolygonState>;

JSI_EXPORT extern const char BaiduMapOverlayPolylineComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayPolyline> component.
 */
using BaiduMapOverlayPolylineShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayPolylineComponentName,
    BaiduMapOverlayPolylineProps,
    BaiduMapOverlayPolylineEventEmitter,
    BaiduMapOverlayPolylineState>;

JSI_EXPORT extern const char BaiduMapOverlayTextComponentName[];

/*
 * `ShadowNode` for <BaiduMapOverlayText> component.
 */
using BaiduMapOverlayTextShadowNode = ConcreteViewShadowNode<
    BaiduMapOverlayTextComponentName,
    BaiduMapOverlayTextProps,
    BaiduMapOverlayTextEventEmitter,
    BaiduMapOverlayTextState>;

JSI_EXPORT extern const char BaiduMapViewComponentName[];

/*
 * `ShadowNode` for <BaiduMapView> component.
 */
using BaiduMapViewShadowNode = ConcreteViewShadowNode<
    BaiduMapViewComponentName,
    BaiduMapViewProps,
    BaiduMapViewEventEmitter,
    BaiduMapViewState>;

} // namespace react
} // namespace facebook
